config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :clients
  resources :time_cards
  root to: 'clients#index'
  get 'index/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :listings do
    member do
      patch  :move
    end
  end

  resources :clients do
    member do
      get :to_do
    end
  end

  resources :time_cards do
    member do
      patch  :edit
    end
  end

  resources :cards do
    member do
      patch  :move
      patch :edit
    end
  end
end

app/views/layouts/_navbar.html.erb
 <!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
      <%= link_to "Clients", clients_path, class:"nav-item pull-left col-md-2"%>
      <%= link_to "Lists", listings_path, class:"nav-item pull-left col-md-2"%>
      <%= link_to "Time", time_cards_path, class:"nav-item pull-left col-md-2"%>

    </div>

    Collect the nav links, forms, and other content for toggling 
    
</nav> -->

<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    Material Dashboard by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!--     Fonts and icons     -->
</head>


<body id='app'>>
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-image="" style="background-color: #fff">
            <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
            <div class="logo">
                <a href="" class="simple-text logo-normal">
                    Work Station 
                </a>
            </div>
 
            <div class="sidebar-wrapper">
                <ul class="nav">
                    <li class="nav-item active ">
                        <a class="nav-link" href="http://localhost:3000/ ">
                            <i class=""></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                     <li class="nav-item">
                       <%= link_to "Listings", listings_path, class:"nav-link nc-icon nc-paper-23", style:"color:grey"%>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Timer", time_cards_path, class:"nav-link nc-icon nc-paper-23", style:"color:grey"%>
                      </li>
                    <li class="nav-item">
                      <%= link_to "Clients", clients_path, class:"nav-link nc-icon nc-paper-23" ,style:"color:grey"%>
                      </li>
                    <li class="nav-item">
                      <%= link_to "Settings", time_cards_path, class:"nav-link nc-icon nc-paper-23", style:"color:grey"%>
                      </li>
                    <li class="nav-item">
                      <%= link_to "Timer", time_cards_path, class:"nav-link nc-icon nc-paper-23", style:"color:grey"%>
                      </li>
                  </ul>
              </div>
           
   <!--  ------------------------------------------ Navbar Footer --------------------------------------------------------------- !-->                       
                    
                    
        
                        
                    </li>
                </ul>
            </div>
        </div>
        <div class="main-panel">
            <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="true" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">dashboard</i>
                  <p class="d-lg-none d-md-block">
                    Stats
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <i class="material-icons">notifications</i>
                  <span class="notification">5</span>
                  <p class="d-lg-none d-md-block">
                    Some Actions
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="#">Mike John responded to your email</a>
                  <a class="dropdown-item" href="#">You have 5 new tasks</a>
                  <a class="dropdown-item" href="#">You're now friend with Andrew</a>
                  <a class="dropdown-item" href="#">Another Notification</a>
                  <a class="dropdown-item" href="#">Another One</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link" href="#pablo" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <a class="dropdown-item" href="#">Profile</a>
                  <a class="dropdown-item" href="#">Settings</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Log out</a>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </nav>

<a href="#" class="float1">
  <i class="fa fa-plus my-float1"></i>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moose</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  
  <body style="background-color:#F4F6FC; zoom: 70%;height:100%;min-height:100%;max-height:100%">
    <%= render 'layouts/navbar'%>
    <div class="container" style="background-color= #F4F6FC; max-width: 100%;height:100%;min-height:100%;margin-top:2%">
      <%= yield %>
    </div>
  </body>
</html>